### ISSUE TITLE
Issues with installing svox

### ISSUE THREAD

**Issue by cititude** [sxyu/volrend#10]
I use `pip install svox` to install svox. However, when I import svox in python, it raises the following warning:

UserWarning: CUDA extension svox.csrc could not be loaded! Operations will be slow.
Please do not import svox in the SVOX source directory.
warn("CUDA extension svox.csrc could not be loaded! "

Platform: ubuntu~16.04.10
Cuda Version: 10.1

Thanks!

**Comment by cititude** [comment]
Solved by reinstalling cuda toolkits

**Comment by justinliang1020** [comment]
did you reinstall the same version of cuda?
