### ISSUE TITLE
how to use web demo to import precomputed PlenOctree files?

### ISSUE THREAD

**Issue by zhangjian94cn** [sxyu/volrend#2]

**Comment by sxyu** [comment]
Hi, the web demo does not currently have an option to select a local file, this would need to be added.
It is possible to type the following in browser developer console to download a .npz file from a remote URL:
`Volrend.load_remote('URL')`
However, also note this shader implementation is about 2x slower than CUDA, so the C++ viewer is recommended.

**Comment by zhangjian94cn** [comment]
thank you!
