### ISSUE TITLE
Octree data exceeds hardward 2D texture limit

### ISSUE THREAD

**Issue by ZJYCP** [sxyu/volrend#5]
Hi, thanks for your work!
When I run the code, the error occurred.
![截图_选择区域_20210428200313](https://user-images.githubusercontent.com/29623776/116400825-10ab0380-a85d-11eb-809e-89dc13c85c03.png)
what should I do? pls

**Comment by sxyu** [comment]
Hi, may I ask which octree is this? Unfortunately it seems it is too large to load on GPU using the shader renderer.
Your GPU driver has certain 2D texture size limits.
You can try making the data smaller by using SH9, higher weight threshold, or less strict bounds.
The CUDA renderer is also more stable & supports larger files.
